# Generated by Django 3.2.7 on 2021-09-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphonenumber',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='owner_phone',
            field=models.ManyToManyField(to='car_contact.UserPhoneNumber'),
        ),
    ]
